(()=>{
const $=id=>document.getElementById(id);
const COLORS={price:'#72efa3',mc:'#70b9ff',rev:'#f3c66f',fdvrev:'#c393ff',yield:'#ff9478',pfdv:'#55d8d0',hfdv:'#85a6ff',pyield:'#f27fa8',hyield:'#ffb06a',pconv:'#9ae6b4',hconv:'#7db8ff'};
const state={data:null,period:90,liveMarket:false};
const selected=new Set(['price_ratio','mc_ratio','fdvrev_ratio','yield_ratio']);
const seriesDefs={
 price_ratio:{label:'价格比 HYPE/PUMP',key:'price_ratio',color:COLORS.price,dash:'solid',format:v=>fmtRatio(v)},
 mc_ratio:{label:'市值比 HYPE/PUMP',key:'mc_ratio',color:COLORS.mc,dash:'solid',format:v=>fmtRatio(v)},
 revenue_ratio:{label:'30D Revenue 比 HYPE/PUMP',key:'revenue_ratio',color:COLORS.rev,dash:'dash',format:v=>fmtRatio(v)},
 fdvrev_ratio:{label:'FDV/Revenue 比 HYPE/PUMP',key:'fdvrev_ratio',color:COLORS.fdvrev,dash:'dash',format:v=>fmtRatio(v)},
 yield_ratio:{label:'Buyback yield 比 HYPE/PUMP',key:'yield_ratio',color:COLORS.yield,dash:'dot',format:v=>fmtRatio(v)},
 p_fdv_rev:{label:'PUMP FDV/Revenue',key:'p_fdv_rev',color:COLORS.pfdv,dash:'dash',format:v=>fmtX(v)},
 h_fdv_rev:{label:'HYPE FDV/Revenue',key:'h_fdv_rev',color:COLORS.hfdv,dash:'dash',format:v=>fmtX(v)},
 p_buyback_yield:{label:'PUMP Buyback yield',key:'p_buyback_yield',color:COLORS.pyield,dash:'dot',format:v=>fmtPct(v)},
 h_buyback_yield:{label:'HYPE Buyback yield',key:'h_buyback_yield',color:COLORS.hyield,dash:'dot',format:v=>fmtPct(v)},
 p_q_conv:{label:'PUMP 季度 Revenue→Buyback',key:'p_q_conv',color:COLORS.pconv,dash:'solid',format:v=>fmtPct(v)},
 h_q_conv:{label:'HYPE 季度 Revenue→Buyback',key:'h_q_conv',color:COLORS.hconv,dash:'solid',format:v=>fmtPct(v)}
};
function finite(v){return Number.isFinite(Number(v))?Number(v):null}
function fmtUSD(n,d=2){n=finite(n);if(n==null)return'—';const a=Math.abs(n);if(a>=1e12)return'$'+(n/1e12).toFixed(d)+'T';if(a>=1e9)return'$'+(n/1e9).toFixed(d)+'B';if(a>=1e6)return'$'+(n/1e6).toFixed(d)+'M';if(a>=1e3)return'$'+(n/1e3).toFixed(d)+'K';return'$'+n.toFixed(d)}
function fmtPrice(n){n=finite(n);if(n==null)return'—';return n<.01?'$'+n.toFixed(6):n<1?'$'+n.toFixed(4):'$'+n.toFixed(2)}
function fmtRatio(n){n=finite(n);if(n==null)return'—';if(Math.abs(n)>=1000)return n.toLocaleString('en-US',{maximumFractionDigits:0})+'×';if(Math.abs(n)>=100)return n.toFixed(1)+'×';return n.toFixed(2)+'×'}
function fmtX(n){n=finite(n);return n==null?'—':n.toFixed(n>=100?0:1)+'×'}
function fmtPct(n){n=finite(n);return n==null?'—':n.toFixed(1)+'%'}
function pctMove(a,b){a=finite(a);b=finite(b);return a&&b?(b/a-1)*100:null}
function fmtMove(n){n=finite(n);return n==null?'—':(n>=0?'+':'')+n.toFixed(1)+'%'}
function ratio(a,b){a=finite(a);b=finite(b);return a!=null&&b? a/b:null}
function setText(id,v){const el=$(id);if(el)el.textContent=v}
function latest(){return state.data&&state.data.current?state.data.current:null}
function rowsWindow(){const rows=(state.data&&Array.isArray(state.data.history))?state.data.history:[];if(!rows.length)return[];const end=new Date(rows[rows.length-1].date+'T00:00:00Z').getTime();const cut=end-state.period*864e5;return rows.filter(r=>new Date(r.date+'T00:00:00Z').getTime()>=cut)}
function renderControls(){const wrap=$('seriesControls');wrap.innerHTML=Object.entries(seriesDefs).map(([id,d])=>`<label class="series-toggle ${selected.has(id)?'active':''}" style="--series:${d.color}" data-dash="${d.dash}"><input type="checkbox" data-series="${id}" ${selected.has(id)?'checked':''}><span class="swatch"></span><span>${d.label}</span></label>`).join('');wrap.querySelectorAll('input[data-series]').forEach(inp=>inp.addEventListener('change',()=>{const id=inp.dataset.series;if(inp.checked)selected.add(id);else selected.delete(id);inp.closest('.series-toggle').classList.toggle('active',inp.checked);drawMaster()}))}
function renderCurrent(){const c=latest();if(!c)return;const p=c.pump||{},h=c.hype||{};const pr=ratio(h.price,p.price),mr=ratio(h.market_cap,p.market_cap),fr=ratio(h.fdv_revenue,p.fdv_revenue),yr=ratio(h.buyback_yield,p.buyback_yield);setText('priceRatio',fmtRatio(pr));setText('mcRatio',fmtRatio(mr));setText('fdvRevRatio',fmtRatio(fr));setText('yieldRatio',fmtRatio(yr));
 const rows=rowsWindow();if(rows.length>1){const a=rows[0],b=rows[rows.length-1];const pm=pctMove(a.price_ratio,b.price_ratio),mm=pctMove(a.mc_ratio,b.mc_ratio);setText('priceRatioMove',fmtMove(pm)+' / '+(state.period===365?'1Y':state.period+'D'));setText('mcRatioMove',fmtMove(mm)+' / '+(state.period===365?'1Y':state.period+'D'));$('priceRatioMove').className='delta '+(pm>=0?'up':'down');$('mcRatioMove').className='delta '+(mm>=0?'up':'down')}
 setText('pPrice',fmtPrice(p.price));setText('hPrice',fmtPrice(h.price));setText('pMC',fmtUSD(p.market_cap));setText('hMC',fmtUSD(h.market_cap));setText('pFDV',fmtUSD(p.fdv));setText('hFDV',fmtUSD(h.fdv));setText('pRev30',fmtUSD(p.revenue_30d));setText('hRev30',fmtUSD(h.revenue_30d));setText('pBuy30',fmtUSD(p.buyback_30d));setText('hBuy30',fmtUSD(h.buyback_30d));setText('pFDVRev',fmtX(p.fdv_revenue));setText('hFDVRev',fmtX(h.fdv_revenue));setText('pYield',fmtPct(p.buyback_yield));setText('hYield',fmtPct(h.buyback_yield));
 setText('tPriceRatio',fmtRatio(pr));setText('tMCRatio',fmtRatio(mr));setText('tFDVRatio',fmtRatio(ratio(h.fdv,p.fdv)));setText('tRevRatio',fmtRatio(ratio(h.revenue_30d,p.revenue_30d)));setText('tBuyRatio',fmtRatio(ratio(h.buyback_30d,p.buyback_30d)));setText('tFDVRevRatio',fmtRatio(fr));setText('tYieldRatio',fmtRatio(yr));
 const q=(state.data.quarters||[]).at(-1)||{};setText('pQConv',fmtPct(q.pump_conversion));setText('hQConv',fmtPct(q.hype_conversion));setText('tQConvRatio',fmtRatio(ratio(q.hype_conversion,q.pump_conversion)));
 setText('pPrice2',fmtPrice(p.price));setText('pMC2',fmtUSD(p.market_cap));setText('pRev302',fmtUSD(p.revenue_30d));setText('pBuy302',fmtUSD(p.buyback_30d));setText('hPrice2',fmtPrice(h.price));setText('hMC2',fmtUSD(h.market_cap));setText('hRev302',fmtUSD(h.revenue_30d));setText('hBuy302',fmtUSD(h.buyback_30d));
 const relRev=ratio(h.revenue_30d,p.revenue_30d);const sentence=pr&&mr?`HYPE/PUMP 价格比 <b>${fmtRatio(pr)}</b>，市值比 <b>${fmtRatio(mr)}</b>；30D Revenue 比为 <b>${fmtRatio(relRev)}</b>。若价格比与基本面比值持续背离，通常比单看绝对涨跌更有信息量。`:'等待有效数据。';$('hero').innerHTML='<strong>当前相对框架：</strong> '+sentence
}
function renderQuarter(){const q=state.data&&Array.isArray(state.data.quarters)?state.data.quarters:[];$('quarterRows').innerHTML=q.length?q.map(x=>`<tr><td>${x.label}${x.partial?'*':''}</td><td>${fmtUSD(x.pump_revenue)}</td><td>${fmtUSD(x.pump_buyback)}</td><td class="pump">${fmtPct(x.pump_conversion)}</td><td>${fmtUSD(x.hype_revenue)}</td><td>${fmtUSD(x.hype_buyback)}</td><td class="hype">${fmtPct(x.hype_conversion)}</td><td class="strong">${fmtRatio(ratio(x.hype_conversion,x.pump_conversion))}</td></tr>`).join(''):'<tr><td colspan="8" class="center muted">暂无季度数据</td></tr>'}
function canvasMetrics(){const canvas=$('chartCanvas'),box=canvas.parentElement,rect=box.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height}}
function activeSeries(rows){return [...selected].map(id=>{const d=seriesDefs[id];const vals=rows.map(r=>finite(r[d.key]));const valid=vals.filter(v=>v!=null);if(valid.length<2)return null;let min=Math.min(...valid),max=Math.max(...valid);if(min===max){const p=Math.abs(min||1)*.05;min-=p;max+=p}const pad=(max-min)*.08;min-=pad;max+=pad;return{id,d,vals,min,max}}).filter(Boolean)}
function drawMaster(){const rows=rowsWindow(),{ctx,w,h}=canvasMetrics(),pad={l:46,r:18,t:18,b:30};ctx.clearRect(0,0,w,h);ctx.font='10px system-ui';ctx.fillStyle='#71877b';ctx.strokeStyle='#1e3028';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad.t+i*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(String(100-i*25),6,y+3)}if(rows.length<2){ctx.fillStyle='#8fa398';ctx.font='12px system-ui';ctx.fillText('暂无足够历史数据',pad.l+10,pad.t+30);renderScale([]);return}
 const act=activeSeries(rows);const x=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,rows.length-1);const y=(v,s)=>pad.t+(s.max-v)*(h-pad.t-pad.b)/(s.max-s.min);const step=Math.max(1,Math.ceil(rows.length/6));rows.forEach((r,i)=>{if(i%step===0||i===rows.length-1){ctx.fillStyle='#71877b';ctx.textAlign='center';ctx.fillText(r.date.slice(5),x(i),h-9)}});ctx.textAlign='left';
 act.forEach(s=>{ctx.strokeStyle=s.d.color;ctx.lineWidth=2.3;ctx.setLineDash(s.d.dash==='dash'?[7,5]:s.d.dash==='dot'?[2,5]:[]);ctx.beginPath();let started=false;s.vals.forEach((v,i)=>{if(v==null){started=false;return}const xx=x(i),yy=y(v,s);if(!started){ctx.moveTo(xx,yy);started=true}else ctx.lineTo(xx,yy)});ctx.stroke();ctx.setLineDash([])});renderScale(act);state._chart={rows,act,pad,w,h,x,y};}
function renderScale(act){const el=$('scaleStrip');el.innerHTML=act.map(s=>{const last=[...s.vals].reverse().find(v=>v!=null);return`<div class="scale-item"><b style="color:${s.d.color}">${s.d.label}</b><div class="scale-range"><span>${s.d.format(s.min)}</span><span>当前 ${s.d.format(last)}</span><span>${s.d.format(s.max)}</span></div></div>`}).join('')||'<div class="scale-item"><b>未选择序列</b><span>勾选上方指标即可绘制</span></div>'}
function showTooltip(ev){const c=state._chart;if(!c||!c.rows.length)return;const canvas=$('chartCanvas'),rect=canvas.getBoundingClientRect(),px=Math.max(c.pad.l,Math.min(c.w-c.pad.r,ev.clientX-rect.left)),idx=Math.round((px-c.pad.l)/(c.w-c.pad.l-c.pad.r)*(c.rows.length-1)),r=c.rows[Math.max(0,Math.min(c.rows.length-1,idx))],tt=$('chartTooltip');tt.innerHTML=`<div class="tt-date">${r.date}</div>`+c.act.map(s=>{const v=finite(r[s.d.key]);return v==null?'':`<div class="tt-row"><span class="tt-line" style="background:${s.d.color}"></span><span>${s.d.label}</span><span class="tt-val">${s.d.format(v)}</span></div>`}).join('');tt.hidden=false;const left=Math.min(c.w-tt.offsetWidth-8,Math.max(8,px+12)),top=Math.max(8,Math.min(c.h-tt.offsetHeight-8,ev.clientY-rect.top-tt.offsetHeight/2));tt.style.left=left+'px';tt.style.top=top+'px'}
function hideTooltip(){const tt=$('chartTooltip');tt.hidden=true}
async function loadSnapshot(){const r=await fetch('data.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('data.json HTTP '+r.status);const d=await r.json();if(!d||!Array.isArray(d.history))throw new Error('invalid data.json');state.data=d;$('dataHealth').className='';$('dataHealthText').textContent='data.json：'+(d.generated_at?new Date(d.generated_at).toLocaleString('zh-CN',{hour12:false}):'已载入');return d}
async function liveMarket(){try{const r=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=pump-fun%2Chyperliquid&price_change_percentage=24h%2C7d%2C30d',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const a=await r.json(),p=a.find(x=>x.id==='pump-fun'),h=a.find(x=>x.id==='hyperliquid');if(!p||!h)throw new Error('coin missing');const c=latest();if(c){Object.assign(c.pump,{price:p.current_price,market_cap:p.market_cap,fdv:p.fully_diluted_valuation||c.pump.fdv});Object.assign(c.hype,{price:h.current_price,market_cap:h.market_cap,fdv:h.fully_diluted_valuation||c.hype.fdv});c.pump.fdv_revenue=c.pump.revenue_30d?c.pump.fdv/(c.pump.revenue_30d*12):c.pump.fdv_revenue;c.hype.fdv_revenue=c.hype.revenue_30d?c.hype.fdv/(c.hype.revenue_30d*12):c.hype.fdv_revenue;c.pump.buyback_yield=c.pump.market_cap?c.pump.buyback_30d*12/c.pump.market_cap*100:c.pump.buyback_yield;c.hype.buyback_yield=c.hype.market_cap?c.hype.buyback_30d*12/c.hype.market_cap*100:c.hype.buyback_yield}state.liveMarket=true;$('liveHealth').className='';$('liveHealthText').textContent='Live price：CoinGecko ✓';return true}catch(e){state.liveMarket=false;$('liveHealth').className='warn';$('liveHealthText').textContent='Live price：失败，保留小时快照';return false}}
function renderAll(){renderCurrent();renderQuarter();drawMaster()}
async function refresh(){const btn=$('refreshBtn');btn.disabled=true;$('app').classList.add('loading');$('status').innerHTML='<span class="live snapshot"></span>刷新 data.json + 公共市场 API…';try{await loadSnapshot()}catch(e){$('dataHealth').className='warn';$('dataHealthText').textContent='data.json：读取失败';}await liveMarket();renderAll();const gen=state.data&&state.data.generated_at?new Date(state.data.generated_at).toLocaleString('zh-CN',{hour12:false}):'未知';$('status').innerHTML='<span class="live '+(state.liveMarket?'':'snapshot')+'"></span>数据快照 '+gen+(state.liveMarket?' · 价格已实时补充':' · 使用快照价格');$('app').classList.remove('loading');btn.disabled=false}
$('periodTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-days]');if(!b)return;state.period=Number(b.dataset.days);document.querySelectorAll('#periodTabs .tab').forEach(x=>x.classList.toggle('active',x===b));renderCurrent();drawMaster()});
$('refreshBtn').addEventListener('click',refresh);$('chartCanvas').addEventListener('pointermove',showTooltip);$('chartCanvas').addEventListener('pointerdown',showTooltip);$('chartCanvas').addEventListener('pointerleave',hideTooltip);window.addEventListener('resize',()=>{clearTimeout(state._rt);state._rt=setTimeout(drawMaster,100)});
renderControls();refresh();
})();