(()=>{
const $=id=>document.getElementById(id);
const fallback={
 p:{price:.005021,mc:1.958e9,fdv:5.021e9,chg24:-3.92,chg7:73.9,chg30:179.2,rev24:1.7798e6,rev7:12e6,rev30:35.67e6,bb30:13.69e6},
 h:{price:80.12,mc:17.82e9,fdv:76.52e9,chg24:3.06,chg7:35.61,chg30:39.61,rev24:1.13e6,rev7:5.78e6,rev30:30.29e6,bb30:30.29e6},
 share:{p:98,h:68.5},
 q:{labels:['Q3 2025','Q4 2025','Q1 2026','Q2 2026','Q3 2026*'],p:[89.98e6,76.51e6,83.02e6,56.01e6,26e6],h:[289.84e6,226.06e6,165.34e6,148.64e6,25.6e6]},
 hist:{dates:['2026-08-17','2026-08-18','2026-08-19','2026-08-20','2026-08-21','2026-08-22','2026-08-23','2026-08-24'],p:[.002943,.002805,.003088,.003660,.004118,.004668,.005226,.005021],h:[59.42,58.61,69.64,73.73,75.45,77.0,79.5,80.12],pmc:[1.045e9,1.10e9,1.21e9,1.43e9,1.61e9,1.82e9,2.04e9,1.958e9],hmc:[12.72e9,13.22e9,15.49e9,16.40e9,16.78e9,17.13e9,17.68e9,17.82e9]}
};
const state=JSON.parse(JSON.stringify(fallback)); state.period=90; state.live={price:false,rev:false,share:false};
const fmtUSD=(n,d=2)=>{if(!Number.isFinite(n))return'—';let a=Math.abs(n),v;if(a>=1e12)v='$'+(n/1e12).toFixed(d)+'T';else if(a>=1e9)v='$'+(n/1e9).toFixed(d)+'B';else if(a>=1e6)v='$'+(n/1e6).toFixed(d)+'M';else if(a>=1e3)v='$'+(n/1e3).toFixed(d)+'K';else v='$'+n.toFixed(d);return v};
const fmtPrice=n=>!Number.isFinite(n)?'—':n<.01?'$'+n.toFixed(6):n<1?'$'+n.toFixed(4):'$'+n.toFixed(2);
const pct=n=>!Number.isFinite(n)?'—':(n>=0?'+':'')+n.toFixed(1)+'%';
const ratioFmt=n=>!Number.isFinite(n)?'—':n<.001?n.toFixed(7):n.toFixed(4);
function setDelta(el,n,label=''){el.textContent=pct(n)+(label?' '+label:'');el.className='delta '+(n>=0?'up':'down')}
function recompute(){
 const p=state.p,h=state.h,ratio=p.price/h.price; $('pPrice').textContent=fmtPrice(p.price);$('hPrice').textContent=fmtPrice(h.price);setDelta($('pChg'),p.chg24,'/ 24H');setDelta($('hChg'),h.chg24,'/ 24H');$('pMC').textContent=fmtUSD(p.mc);$('hMC').textContent=fmtUSD(h.mc);$('pFDV').textContent=fmtUSD(p.fdv);$('hFDV').textContent=fmtUSD(h.fdv);$('ratioNow').textContent=ratioFmt(ratio);
 const rs30=((1+p.chg30/100)/(1+h.chg30/100)-1)*100;setDelta($('ratio30'),rs30,'/ 30D relative');
 ['24','7','30'].forEach(w=>{const key=w==='24'?'rev24':w==='7'?'rev7':'rev30';$('pRev'+w+(w==='30'?'b':'')).textContent=fmtUSD(p[key]);$('hRev'+w+(w==='30'?'b':'')).textContent=fmtUSD(h[key])});
 $('pRev30').textContent=fmtUSD(p.rev30);$('hRev30').textContent=fmtUSD(h.rev30);$('revLead').textContent='PUMP ≈ '+(p.rev30/h.rev30).toFixed(2)+'× HYPE';
 const pa=p.rev30*12,ha=h.rev30*12;$('pAnnual').textContent=fmtUSD(pa);$('hAnnual').textContent=fmtUSD(ha);$('pMCRev').textContent=(p.mc/pa).toFixed(1)+'×';$('hMCRev').textContent=(h.mc/ha).toFixed(1)+'×';$('pFDVRev').textContent=(p.fdv/pa).toFixed(1)+'×';$('hFDVRev').textContent=(h.fdv/ha).toFixed(1)+'×';$('pBB30').textContent=fmtUSD(p.bb30);$('hBB30').textContent=fmtUSD(h.bb30);$('pYield').textContent=((p.bb30*12/p.mc)*100).toFixed(1)+'%';$('hYield').textContent=((h.bb30*12/h.mc)*100).toFixed(1)+'%';
 $('pMCLatest').textContent=fmtUSD(p.mc);$('hMCLatest').textContent=fmtUSD(h.mc);
 const rsClass=rs30>5?'PUMP 相对走强':rs30<-5?'HYPE 相对走强':'相对均衡'; const valP=p.mc/pa,valH=h.mc/ha; $('hero').innerHTML='<strong>当前读数：</strong> '+rsClass+'；30D Revenue 为 <span class="pump">'+fmtUSD(p.rev30)+'</span> vs <span class="hype">'+fmtUSD(h.rev30)+'</span>。按 30D 运行率，PUMP MC/Revenue ≈ <b>'+valP.toFixed(1)+'×</b>，HYPE ≈ <b>'+valH.toFixed(1)+'×</b>。倍数差必须结合 PUMP 的周期性/解锁与 HYPE 的产品期权价值一起判断。';
}
function lineSVG(container,series,opt={}){const el=$(container);if(!series||series.length<2){el.innerHTML='<div class="chart-empty">暂无足够历史数据</div>';return}const W=900,H=260,p={l:58,r:16,t:16,b:30};let vals=series.map(x=>x.v).filter(Number.isFinite);let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min*=.95;max*=1.05}const pad=(max-min)*.08;min-=pad;max+=pad;const x=i=>p.l+i*(W-p.l-p.r)/(series.length-1);const y=v=>p.t+(max-v)*(H-p.t-p.b)/(max-min);let s='<svg viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none" aria-label="'+(opt.label||'chart')+'">';for(let i=0;i<5;i++){const v=min+(max-min)*i/4,yy=y(v);s+='<line x1="'+p.l+'" x2="'+(W-p.r)+'" y1="'+yy+'" y2="'+yy+'" stroke="#22332b" stroke-width="1"/><text x="4" y="'+(yy+4)+'" fill="#71877b" font-size="10">'+(opt.format?opt.format(v):v.toPrecision(3))+'</text>'}const step=Math.max(1,Math.ceil(series.length/6));series.forEach((d,i)=>{if(i%step===0||i===series.length-1)s+='<text x="'+x(i)+'" y="'+(H-8)+'" text-anchor="middle" fill="#71877b" font-size="9">'+d.d.slice(5)+'</text>'});s+='<polyline points="'+series.map((d,i)=>x(i)+','+y(d.v)).join(' ')+'" fill="none" stroke="'+(opt.color||'#72efa3')+'" stroke-width="3" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/>';const last=series[series.length-1];s+='<circle cx="'+x(series.length-1)+'" cy="'+y(last.v)+'" r="4" fill="'+(opt.color||'#72efa3')+'" vector-effect="non-scaling-stroke"/></svg>';el.innerHTML=s}
function getWindow(){const hist=state.hist,n=hist.dates.length;if(!n)return[];const anchor=new Date(hist.dates[n-1]+'T00:00:00Z').getTime(); const cutoff=anchor-state.period*864e5;let idx=hist.dates.findIndex(d=>new Date(d+'T00:00:00Z').getTime()>=cutoff);if(idx<0)idx=0;return hist.dates.map((d,i)=>({d,p:hist.p[i],h:hist.h[i],pmc:hist.pmc[i],hmc:hist.hmc[i]})).slice(idx)}
function renderHistory(){const rows=getWindow().filter(x=>[x.p,x.h].every(Number.isFinite));const ratio=rows.map(x=>({d:x.d,v:x.p/x.h}));lineSVG('ratioChart',ratio,{color:'#72efa3',label:'PUMP/HYPE price ratio',format:ratioFmt});lineSVG('pMCChart',rows.filter(x=>Number.isFinite(x.pmc)).map(x=>({d:x.d,v:x.pmc})),{color:'#72efa3',label:'PUMP market cap',format:v=>fmtUSD(v,1)});lineSVG('hMCChart',rows.filter(x=>Number.isFinite(x.hmc)).map(x=>({d:x.d,v:x.hmc})),{color:'#70b9ff',label:'HYPE market cap',format:v=>fmtUSD(v,1)});if(ratio.length){let a=ratio[0].v,b=ratio[ratio.length-1].v,m=(b/a-1)*100;$('ratioStart').textContent=ratioFmt(a);$('ratioEnd').textContent=ratioFmt(b);$('ratioMove').textContent=pct(m);$('ratioMove').className=m>=0?'up':'down'}$('ratioRange').textContent=state.period===365?'1Y':state.period+'D'}
function renderQuarter(){const q=state.q,max=Math.max(...q.p,...q.h,1),bars=$('buybackBars');bars.innerHTML=q.labels.map((lab,i)=>'<div class="qgroup"><div class="qbar p" style="height:'+Math.max(2,q.p[i]/max*100)+'%"><span class="qtip">'+fmtUSD(q.p[i],1)+'</span></div><div class="qbar h" style="height:'+Math.max(2,q.h[i]/max*100)+'%"><span class="qtip">'+fmtUSD(q.h[i],1)+'</span></div><span class="qlabel">'+lab.replace(' 20',' ’')+'</span></div>').join('');$('qRows').innerHTML=q.labels.map((lab,i)=>'<tr><td>'+lab+'</td><td class="pump">'+fmtUSD(q.p[i])+'</td><td class="hype">'+fmtUSD(q.h[i])+'</td><td>'+(q.p[i]>0?(q.h[i]/q.p[i]).toFixed(2)+'×':'—')+'</td></tr>').join('')}
function renderShare(){let p=Math.max(0,Math.min(100,state.share.p)),h=Math.max(0,Math.min(100,state.share.h));$('pShare').textContent=p.toFixed(1)+'%';$('hShare').textContent=h.toFixed(1)+'%';$('pShareBar').style.width=p+'%';$('hShareBar').style.width=h+'%'}
function seriesFrom(obj){let a=obj&&obj.totalDataChart;if(!Array.isArray(a))return[];return a.map(x=>{let ts=Array.isArray(x)?x[0]:null,v=Array.isArray(x)?x[1]:null;if(v&&typeof v==='object')v=Object.values(v).reduce((s,n)=>s+(Number(n)||0),0);return[Number(ts),Number(v)]}).filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1]))}
function sumLast(series,days){if(!series.length)return NaN;const last=series[series.length-1][0],cut=last-(days-1)*86400;return series.filter(x=>x[0]>=cut).reduce((s,x)=>s+x[1],0)}
function quarterly(series){const out={};series.forEach(([ts,v])=>{const d=new Date(ts*1000),q='Q'+(Math.floor(d.getUTCMonth()/3)+1)+' '+d.getUTCFullYear();out[q]=(out[q]||0)+v});return out}
async function jf(url){const r=await fetch(url,{cache:'no-store',headers:{'accept':'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function getLlama(slugs,type){let err;for(const slug of slugs){try{return await jf('https://api.llama.fi/summary/fees/'+encodeURIComponent(slug)+'?dataType='+type)}catch(e){err=e}}throw err||new Error('no llama slug')}
async function loadPrices(){try{const m=await jf('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=pump-fun%2Chyperliquid&price_change_percentage=24h%2C7d%2C30d');const p=m.find(x=>x.id==='pump-fun'),h=m.find(x=>x.id==='hyperliquid');if(!p||!h)throw new Error('coin missing');Object.assign(state.p,{price:p.current_price,mc:p.market_cap,fdv:p.fully_diluted_valuation||p.current_price*(p.total_supply||1e12),chg24:p.price_change_percentage_24h,chg7:p.price_change_percentage_7d_in_currency,chg30:p.price_change_percentage_30d_in_currency});Object.assign(state.h,{price:h.current_price,mc:h.market_cap,fdv:h.fully_diluted_valuation||h.current_price*(h.total_supply||955e6),chg24:h.price_change_percentage_24h,chg7:h.price_change_percentage_7d_in_currency,chg30:h.price_change_percentage_30d_in_currency});
 const [ph,hh]=await Promise.all([jf('https://api.coingecko.com/api/v3/coins/pump-fun/market_chart?vs_currency=usd&days=365&interval=daily'),jf('https://api.coingecko.com/api/v3/coins/hyperliquid/market_chart?vs_currency=usd&days=365&interval=daily')]);const mapChart=o=>{const mp=new Map((o.prices||[]).map(x=>[new Date(x[0]).toISOString().slice(0,10),x[1]])),mm=new Map((o.market_caps||[]).map(x=>[new Date(x[0]).toISOString().slice(0,10),x[1]]));return{mp,mm}};const P=mapChart(ph),H=mapChart(hh),dates=[...P.mp.keys()].filter(d=>H.mp.has(d)).sort();state.hist={dates,p:dates.map(d=>P.mp.get(d)),h:dates.map(d=>H.mp.get(d)),pmc:dates.map(d=>P.mm.get(d)),hmc:dates.map(d=>H.mm.get(d))};state.live.price=true;$('priceHealth').className='';$('priceHealthText').textContent='CoinGecko：实时 + 1Y 历史 ✓';return true}catch(e){state.live.price=false;$('priceHealth').className='warn';$('priceHealthText').textContent='CoinGecko：API 限流/CORS，使用快照';return false}}
async function loadRevenue(){try{const [pr,hr,pb,hb]=await Promise.all([getLlama(['pump','pump.fun','pumpdotfun'],'dailyRevenue'),getLlama(['hyperliquid'],'dailyRevenue'),getLlama(['pump','pump.fun','pumpdotfun'],'dailyHoldersRevenue'),getLlama(['hyperliquid'],'dailyHoldersRevenue')]);const P=seriesFrom(pr),H=seriesFrom(hr),PB=seriesFrom(pb),HB=seriesFrom(hb);if(!P.length||!H.length)throw new Error('empty revenue series');state.p.rev24=sumLast(P,1);state.h.rev24=sumLast(H,1);state.p.rev7=sumLast(P,7);state.h.rev7=sumLast(H,7);state.p.rev30=sumLast(P,30);state.h.rev30=sumLast(H,30);if(PB.length){state.p.bb30=sumLast(PB,30)}if(HB.length){state.h.bb30=sumLast(HB,30)}const qp=quarterly(PB),qh=quarterly(HB),labels=['Q3 2025','Q4 2025','Q1 2026','Q2 2026','Q3 2026'];state.q={labels:labels.map((x,i)=>i===labels.length-1?x+'*':x),p:labels.map(x=>Number.isFinite(qp[x])?qp[x]:(fallback.q.p[labels.indexOf(x)]||0)),h:labels.map(x=>Number.isFinite(qh[x])?qh[x]:(fallback.q.h[labels.indexOf(x)]||0))};state.live.rev=true;$('revHealth').className='';$('revHealthText').textContent='DefiLlama：Revenue + holders revenue ✓';return true}catch(e){state.live.rev=false;$('revHealth').className='warn';$('revHealthText').textContent='DefiLlama：API 不可用，使用快照';return false}}
async function loadShares(){let pOk=false,hOk=false;try{const o=await jf('https://api.llama.fi/overview/fees?dataType=dailyRevenue&excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true');const ps=Array.isArray(o.protocols)?o.protocols:[];const launch=ps.filter(x=>String(x.category||'').toLowerCase().includes('launch')||/pump|bonk|bags|believe|launchlab|flap/i.test(String(x.name||''))).filter(x=>Number(x.total30d)>0);const pump=launch.find(x=>/pump/i.test(String(x.name||'')));const total=launch.reduce((s,x)=>s+Number(x.total30d||0),0);if(pump&&total>0&&launch.length>=2){state.share.p=Number(pump.total30d)/total*100;pOk=true}}catch(e){}
 try{const o=await jf('https://api.llama.fi/overview/derivatives?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true');const ps=Array.isArray(o.protocols)?o.protocols:[];const h=ps.find(x=>/hyperliquid/i.test(String(x.name||'')));const total=Number(o.total30d)||ps.reduce((s,x)=>s+Number(x.total30d||0),0);if(h&&total>0){state.share.h=Number(h.total30d)/total*100;hOk=true}}catch(e){}
 state.live.share=pOk||hOk;$('shareHealth').className=(pOk||hOk)?'':'warn';$('shareHealthText').textContent='Market share：'+(pOk?'PUMP live ':'PUMP snapshot ')+(hOk?'· HYPE live':'· HYPE snapshot');$('shareNote').textContent=(pOk?'PUMP 使用 DefiLlama Launchpad/known-peer 30D revenue 动态份额。':'PUMP fallback：2026-08-09 tracked launchpad daily revenue share ≈98%。')+' '+(hOk?'HYPE 使用 DefiLlama derivatives 30D category share。':'HYPE fallback：DefiLlama 近期 tracked peer set 30D derivatives volume share ≈68.5%。');return pOk||hOk}
async function refreshAll(){const b=$('refreshBtn');b.disabled=true;$('app').classList.add('loading');$('status').innerHTML='<span class="live snapshot"></span>正在并行刷新 CoinGecko / DefiLlama…';await Promise.allSettled([loadPrices(),loadRevenue(),loadShares()]);recompute();renderHistory();renderQuarter();renderShare();const ok=[state.live.price,state.live.rev,state.live.share].filter(Boolean).length,now=new Date().toLocaleString('zh-CN',{hour12:false});$('status').innerHTML='<span class="live '+(ok<2?'snapshot':'')+'"></span>'+now+' · '+(ok===3?'公开 API 全部更新':ok+' / 3 数据组更新，其余保留快照');$('app').classList.remove('loading');b.disabled=false}
$('periodTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-days]');if(!b)return;state.period=Number(b.dataset.days);document.querySelectorAll('#periodTabs .tab').forEach(x=>x.classList.toggle('active',x===b));renderHistory()});$('refreshBtn').addEventListener('click',refreshAll);
recompute();renderHistory();renderQuarter();renderShare();refreshAll();
})();
